#!/bin/bash

########################################
# Defaults
########################################
DEFAULT_TARGET="172.16.2.56"
DEFAULT_WORKDIR="/micros/esp32/BTRGB"

########################################
# Colours
########################################
col_def="\e[39m"
col_red="\e[31m"
col_gre="\e[32m"
col_yel="\e[33m"
col_blu="\e[34m"
col_mag="\e[35m"
col_cya="\e[36m"
col_grey="\e[37m"
col_gray="\e[38m"
col_lred="\e[91m"
col_lgre="\e[92m"
col_lyel="\e[93m"
col_lblu="\e[94m"
col_lmag="\e[95m"
col_lcya="\e[96m"
col_whi="\e[97m"

unset HTTP_PROXY
unset http_proxy
unset all_proxy

# ##########################################
# Which command is being called
# ##########################################
COMMAND=$(basename $0)

# ##########################################
# If we have a 'main' directory and a 'Makefile' assume we are located
# in our desired working directory
# ##########################################
if [ -d main -a -f Makefile ]
then
  WORKDIR=$(pwd)
else
  WORKDIR=${DEFAULT_WORKDIR}
  cd ${WORKDIR}

  if [ ! -f Makefile ]
  then
    echo "No Makefile!"
    exit
  fi
fi

# ##########################################
# Get our project name
# ##########################################
PROJECT=$(awk '$1 ~ /PROJECT_NAME/ {print $3}' < Makefile)

# ##########################################
# (App Main)
# ##########################################
if [ ${COMMAND} == "ota" ]
then
  BIN_PATH="build/${PROJECT}.bin"

  if [ $# -eq 1 ]
  then
    TARGET=${1}
  else
    TARGET=${DEFAULT_TARGET}
  fi

  ~/bin/update_firmware.py ${TARGET} ${BIN_PATH}
fi
